---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: frontend-app
        image: oussamasebai/front_pfe:1.0 
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
